# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

# Note that this file is NOT used to automatically manage dependencies for the
# local compute target. To provision these dependencies locally, run:
# conda env update --file conda_dependencies.yml

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For managing Spark packages and configuration, see spark_dependencies.yml.

# This directive is stored in a comment to preserve the Conda file structure.

name: project_environment
dependencies:
  # The python interpreter version.
  - python=3.5.2
  # Required for Jupyter Notebooks.

  - pip:
    # Packages required for CNTK and Faster-R-CNN
    - easydict
    - pyyaml
    - pillow
    - pandas
    - Flask
    - scipy
    - setuptools
    - numpy
    - pyshp
